version: "3"
services:
  php:
    image: xianzixiang/jupyter_grader:dl_2.0 
    network_mode: "host"
    volumes:
      - ./:/var/www/html
    tty: true
#    command: tail -F /dev/null
#    ports:
#      - "8199:80"
