version: '3.0'

services:
  app:
    # image: 
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "9222:22"
      - "9180:80"
    devices:
    # use `python -m serial.tools.miniterm` to see what the name is of the printer
      - /dev/ttyUSB0:/dev/ttyACM0
      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
    volumes:
      - ./container:/debug
      - octoprint:/octoprint
    container_name: octo
    entrypoint:
      ["/bin/bash", "-c", "/bin/bash /opt/start.sh"]

#   config-editor:
#     image: linuxserver/code-server
#     ports:
#       - 9043:8443
#     depends_on:
#       - app
#     restart: unless-stopped
#     environment:
#       - PUID=0
#       - GUID=0
#       - TZ=Asia/Shanghai
#     container_name: octo_editor
#     volumes:
#       - octoprint:/octoprint

volumes:
  octoprint:
